In [2]:
import pandas as pd
df = pd.read_excel("D:/files/Code/DecodeLabs-internship/Data/cleaned_dataset.xlsx")
df

,OrderID,Date,Year,Month,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,200000,2023-01-04,2023,1,72649,Monitor,5,570.62,928,Debit Card,Shipped,37947903,7,SAVE10,Instagram,2853.10
1,200001,2024-08-23,2024,8,75739,Phone,2,151.35,823,Online,Shipped,91186779,3,SAVE10,Referral,302.70
2,200002,2024-02-27,2024,2,81728,Tablet,5,550.68,512,Credit Card,Cancelled,42903982,8,FREESHIP,Email,2753.40
3,200003,2023-10-15,2023,10,33540,Chair,1,273.19,275,Debit Card,Returned,62788070,5,SAVE10,Facebook,273.19
4,200004,2025-05-08,2025,5,81840,Printer,4,626.01,668,Online,Delivered,29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,201195,2024-06-20,2024,6,21126,Desk,1,107.04,392,Credit Card,Cancelled,38009181,6,FREESHIP,Google,107.04
1196,201196,2024-03-04,2024,3,20095,Monitor,2,662.53,778,Online,Cancelled,69207593,5,No_Coupon,Facebook,1325.06
1197,201197,2023-07-13,2023,7,79674,Tablet,2,436.84,275,Online,Delivered,88039356,2,FREESHIP,Instagram,873.68
1198,201198,2024-08-22,2024,8,64753,Chair,4,262.52,509,Debit Card,Cancelled,71683331,4,WINTER15,Instagram,1050.08
1199,201199,2023-06-11,2023,6,57502,Tablet,4,560.58,201,Gift Card,Returned,51116746,6,SAVE10,Referral,2242.32

In [2]:
df['CouponCode']=df['CouponCode'].fillna('No_Coupon')
print(df['CouponCode'].isnull().sum())
print(df['CouponCode'].value_counts())

0
CouponCode
FREESHIP     313
No_Coupon    309
WINTER15     292
SAVE10       286
Name: count, dtype: int64

In [3]:
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,No_Coupon,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 131.4 KB

In [5]:
cat_cols = ['OrderStatus', 'Product', 'PaymentMethod', 'ReferralSource', 'CouponCode']

for col in cat_cols:
    print(f"{col}: {df[col].nunique()} unique → {df[col].unique()}")

OrderStatus: 5 unique → <StringArray>
['Shipped', 'Cancelled', 'Returned', 'Delivered', 'Pending']
Length: 5, dtype: str
Product: 7 unique → <StringArray>
['Monitor', 'Phone', 'Tablet', 'Chair', 'Printer', 'Laptop', 'Desk']
Length: 7, dtype: str
PaymentMethod: 5 unique → <StringArray>
['Debit Card', 'Online', 'Credit Card', 'Gift Card', 'Cash']
Length: 5, dtype: str
ReferralSource: 5 unique → <StringArray>
['Instagram', 'Referral', 'Email', 'Facebook', 'Google']
Length: 5, dtype: str
CouponCode: 4 unique → <StringArray>
['SAVE10', 'FREESHIP', 'No_Coupon', 'WINTER15']
Length: 4, dtype: str

In [6]:
for col in cat_cols:
    df[col] = df[col].astype('category')
print(df[cat_cols].dtypes)

OrderStatus       category
Product           category
PaymentMethod     category
ReferralSource    category
CouponCode        category
dtype: object

In [7]:
 print(df.memory_usage(deep=True).sum() / 1024, "KB")

327.3369140625 KB

In [8]:
df['UnitPrice'] = df['UnitPrice'].round(2)
df['TotalPrice'] = df['TotalPrice'].round(2)

In [9]:
df['calculated'] = (df['Quantity'] * df['UnitPrice']).round(2)
df['discount_rate'] = ((df['calculated'] - df['TotalPrice']) / df['calculated']).round(4)

print(df.groupby('CouponCode')['discount_rate'].unique())

CouponCode
FREESHIP     [0.0]
No_Coupon    [0.0]
SAVE10       [0.0]
WINTER15     [0.0]
Name: discount_rate, dtype: object

In [10]:
df.drop(columns=['calculated', 'discount_rate'], inplace=True)

In [11]:
str_cols = ['OrderID', 'CustomerID', 'Product', 'ShippingAddress',
            'PaymentMethod', 'OrderStatus', 'TrackingNumber',
            'ReferralSource', 'CouponCode']

for col in str_cols:
    df[col] = df[col].str.strip()

# spot check a few categorical ones for casing issues
for col in ['OrderStatus', 'Product', 'PaymentMethod']:
    print(f"{col}: {sorted(df[col].unique())}")

OrderStatus: ['Cancelled', 'Delivered', 'Pending', 'Returned', 'Shipped']
Product: ['Chair', 'Desk', 'Laptop', 'Monitor', 'Phone', 'Printer', 'Tablet']
PaymentMethod: ['Cash', 'Credit Card', 'Debit Card', 'Gift Card', 'Online']

In [12]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month

print(df[['Date', 'Year', 'Month']].head())

        Date  Year  Month
0 2023-01-04  2023      1
1 2024-08-23  2024      8
2 2024-02-27  2024      2
3 2023-10-15  2023     10
4 2025-05-08  2025      5

In [13]:
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Year,Month
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2023,1
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,2024,8
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2024,2
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,2023,10
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2025,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04,2024,6
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,No_Coupon,Facebook,1325.06,2024,3
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68,2023,7
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08,2024,8
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32,2023,6

In [14]:
df.insert(2, 'Year', df.pop('Year'))
df.insert(3, 'Month', df.pop('Month'))

print(df.columns.tolist())

['OrderID', 'Date', 'Year', 'Month', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

In [15]:
df

,OrderID,Date,Year,Month,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,2023,1,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,2024,8,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,2024,2,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,2023,10,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,2025,5,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,2024,6,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,2024,3,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,No_Coupon,Facebook,1325.06
1197,ORD201197,2023-07-13,2023,7,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,2024,8,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,2023,6,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [16]:
df['ShippingAddress'] = df['ShippingAddress'].str.replace(' Main St', '', regex=False)
df['ShippingAddress'].head()

0    928
1    823
2    512
3    275
4    668
Name: ShippingAddress, dtype: str

In [17]:
df

,OrderID,Date,Year,Month,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,2023,1,C72649,Monitor,5,570.62,928,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,2024,8,C75739,Phone,2,151.35,823,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,2024,2,C81728,Tablet,5,550.68,512,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,2023,10,C33540,Chair,1,273.19,275,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,2025,5,C81840,Printer,4,626.01,668,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,2024,6,C21126,Desk,1,107.04,392,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,2024,3,C20095,Monitor,2,662.53,778,Online,Cancelled,TRK69207593,5,No_Coupon,Facebook,1325.06
1197,ORD201197,2023-07-13,2023,7,C79674,Tablet,2,436.84,275,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,2024,8,C64753,Chair,4,262.52,509,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,2023,6,C57502,Tablet,4,560.58,201,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [18]:
df['CustomerID'] = df['CustomerID'].str.replace('C', '', regex=False)

In [19]:
df['OrderID'] = df['OrderID'].str.replace('ORD', '', regex=False)

In [20]:
df['TrackingNumber'] = df['TrackingNumber'].str.replace('TRK', '', regex=False)